title: thepapercoder.github.io
email: nguyengiangson12@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The paper coder blog about technology, coding and life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "thepapercoder.github.io"
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: The Paper Coder
  tagline: Software Engineer
  date_format: "%b %-d, %Y"
  sitemap: true
  disqus_shortname: thepapercoder

  navigation:
    - title: About me
      url: "/about"

  social_links:
    github: thepapercoder
    linkedIn: in/nguyen-giang-son
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed