# Setup
title:        Son Giang Nguyen
tagline:      My personal GitHub Pages
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       Son Giang Nguyen
  url:        https://github.com/thepapercoder

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
